---
title: "Class Data"
output:
  html_document:
    df_print: paged
---
```{r}

text = getURL('https://raw.githubusercontent.com/fabzy4L/DATA_ANALYTICS/main/
cddf <- read.csv(text = getURL('https://raw.githubusercontent.com/fabzy4L/DATA_ANALYTICS/main/BIOSTATISTICS_COURSE_PROJECTS/Class-data.csv'))

ID <- cddf$ID
Height.cm <- cddf$Height.cm
Handedness <- cddf$Handedness
Dominant.Foot <- cddf$Dominant.Foot
Dominant.Eye <- cddf$Dominant.Eye
Year <- cddf$Year
Sex <- cddf$Sex
Number.Siblings <- cddf$Number.Siblings
CircumferenceHead.com <- cddf$CircumferenceHead.com


```


```{r}
#mean
mean(Height.cm)

#median
median(Height.cm)

#standard deviation
sd(Height.cm)

#standard error
se <- function(x) sd(x)/sqrt(length(x))
x = Height.cm
se(x)

#minimum
min(Height.cm)

#maximum
max(Height.cm)

#25th, 50th, 75th, 97.5th percentile
quantile(Height.cm, probs = c(0.25, 0.50, 0.75, 0.975))
```
```{r}

#confidence interval

n <-with(cddf, length(ID))
m <-mean(Height.cm)
s <-sd(Height.cm)

# Z- value for 95%
z = 1.960

#Error
error <- z*(s/(sqrt(n)))
error

#Confidence interval range lower end
m - error
#Confidence interval range upper end
m + error


```
```{r}
#histogram
hist(Height.cm)

```
```{r}

#e. Mean Heights per sex
tapply(Height.cm, Sex, mean)

```
```{r}

#f. right handed
table(Handedness)

```
```{r}
#g. Sex vs Height average
y2 <-with(cddf, tapply(Height.cm, Sex, mean))
barplot(y2)

```
```{r}

#h. height and head circumference
plot(CircumferenceHead.com,Height.cm)
abline(lm(Height.cm~CircumferenceHead.com))

```
```{r}
