---
title: "R Notebook"
output: html_notebook
---

```{r}
coatings <- read.csv('/Users/f4L/Documents/GitHub/RStudioDataAnalysis/BIOSTATISTICS COURSE PROJECTS/coatings.csv')
coatings
```


```{r}
site<-coatings$site
batch<-coatings$batch
coating<-coatings$coating

A <- coatings[1:15,1:3]
B <- coatings[16:30,1:3]
shapiro.test(coatings$coating)
shapiro.test(A$coating)
shapiro.test(B$coating)
```



```{r}
interaction.plot(coatings$batch,coatings$site,coatings$coating, ylim = c(4.5,5.5), ylab = "Coating", xlab = "Batch", legend = 0)
legend("topleft", c("Site A", "Site B"),lty=c(2:1),col=c("black"), cex=0.7)

```


```{r}
#1A. ANOVA OF SEVERAL FACTORS - There is no significant difference between the thickness of samples among sites, however, there is a very strong and statistically significant evidence of difference in thinckness among batches. 
anova(lm(coatings$coating~coatings$site/coatings$batch))
honestly.significant <- TukeyHSD(aov(coatings$coating~coatings$site/coatings$batch))
honestly.significant
```
```{r}
par(mfrow=c(1,2))
plot(honestly.significant)

```
```{r}
dog.digitalis <- read.csv('/Users/f4L/Documents/GitHub/RStudioDataAnalysis/BIOSTATISTICS COURSE PROJECTS/dog.digitalis.csv')

#2A. Per this graph, it is inferred that Treatment C presents a greater degree of calcium in any given dogs heart when compared to either B or A. 
interaction.plot(dog.digitalis$Dog,dog.digitalis$Treatment,dog.digitalis$Calcium, xlab = "Dog", ylab = "Calcium", legend= 0)
legend("topright", c("Treatment C","Treatment B","Treatment A"),lty=c(1:3),col=c("black"), cex=0.7)
```

```{r}
#Treatments show evidence of greated statistically significant effect on calcium than the dog type does. Hence we can assume that the calcium intake is mostly associated to the treatment (i.e. the contained calcium per digitalis)
shapiro.test(dog.digitalis$Calcium)
anova(lm(dog.digitalis$Calcium~dog.digitalis$Treatment+dog.digitalis$Dog))
TukeyHSD(aov(dog.digitalis$Calcium~dog.digitalis$Treatment+dog.digitalis$Dog))
```
```{r}
bushtucker <- read.csv('/Users/f4L/Documents/GitHub/RStudioDataAnalysis/BIOSTATISTICS COURSE PROJECTS/bushtucker.csv')
```


```{r}
participant <- as.double(bushtucker$Participant)
Stick.Insect <- bushtucker[c(3,7,11,15,19,23,27,31),c(1:3)]
Fish.Eye <- bushtucker[c(1,5,9,13,17,21,25,29),c(1:3)]
Roo.Testicle <- bushtucker[c(2,6,10,14,18,22,26,30),c(1:3)]
Witchetty.grub <-bushtucker[c(4,8,12,16,20,24,28,32),c(1:3)]
participant.si <- (Stick.Insect$Participant)
participant.fe <- (Fish.Eye$Participant)
participant.rt <- (Roo.Testicle$Participant)
participant.wg <- (Witchetty.grub$Participant)

interaction.plot(bushtucker$Participant,bushtucker$Animal,bushtucker$Retch, legend = 0,xlab = "Paticipant", ylab = "Time until Retch (s)")
legend("topleft", c("Stick Insect","Fish Eye","Roo Testicle", "Witchetty grub"),lty=c(2,4,3,1),col=c("black"), cex=0.7)
```
```{r}
## 3A. Upon analysis, Stick insect and Fish eye presented a very large difference, as well as to the Roo testicle. Roo Testicle were vert close to each other in the retching effect on participants. Stick Insect presented the lesser retching effect upon participants. 
model <- ezANOVA(data=bushtucker, dv=(Retch), wid=(Participant), within=(Animal), detailed=TRUE, type=3)
pairwise.t.test(Retch, Animal, paired=TRUE, p.adjust.method = "holm")

```

